name: prebuild

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: matdsoupe
          authToken: '${{ secrets.CACHIX_TOKEN }}'
      - run: nix-shell -p nixFlakes --run 'nix-build build.nix' | cachix push matdsoupe
      - run: nix-shell -p nixFlakes --run 'nix build .#nixosConfigurations.acer-nix.config.system.build.toplevel --experimental-features "nix-command flakes"' | cachix push matdsoupe
      - run: nix-shell -p nixFlakes --run 'nix build .#nixosConfigurations.vps.config.system.build.toplevel --experimental-features "nix-command flakes"' | cachix push matdsoupe
